MatheusDiass/myleveling

src/App.vue
src/components/Mylev-Footer.vue

Criação do footer

---

src/router/index.js
src/views/Mylev-Home.vue

Criação da view home

---

src/components/Mylev-ContentName.vue
src/components/Mylev-Footer.vue
src/components/Mylev-Navbar.vue
src/views/Mylev-Home.vue

Criação do Card de Matérias

---

src/App.vue
src/router/index.js
src/views/Mylev-Register.vue

Criação da view Register

---

src/configuration/configuration.json
src/store/actions.js
src/store/getters.js
src/store/index.js
src/store/mutationTypes.js
src/store/mutations.js
src/store/state.js

Criação dos arquivos do Vuex para o aviso de erro e de sucesso.

Criação dos arquivos do Vuex para o aviso de erro e de sucesso

---

src/components/Mylev-ContentName.vue
src/components/Mylev-Footer.vue
src/components/Mylev-LoginCard.vue
src/components/Mylev-Navbar.vue
src/components/Mylev-RegisterCard.vue
src/router/index.js
src/views/Mylev-Home.vue
src/views/Mylev-Login.vue
src/views/Mylev-Register.vue

Organização do código e adicionada algumas rotas nos menus(Home, Login)

Organização do código e adicionada algumas rotas nos menus

---

src/components/Mylev-ErrorPopup.vue

Criação do Popup

---

src/components/Mylev-ErrorPopup.vue
src/components/Mylev-SubjectCard.vue

Criação do SubjectCard

---

src/router/index.js
src/views/Mylev-Subject.vue

Criação da view Subject

---

src/App.vue
src/components/Mylev-ContentName.vue
src/components/Mylev-LoginCard.vue
src/components/Mylev-RegisterCard.vue
src/configuration/configuration.json
src/store/index.js
src/store/modules/Subject/actions.js
src/store/modules/Subject/getters.js
src/store/modules/Subject/index.js
src/store/modules/Subject/mutations.js
src/store/modules/Subject/mutationsTypes.js
src/store/modules/Subject/state.js
src/views/Mylev-Home.vue

Criado método que traz os nomes das máterias da API para a página home e ajustado o grid da mesma.

Craida a requisição para trazer o nome das matérias e ajustado o grid

---

src/App.vue
src/components/Mylev-Alert.vue
src/views/Mylev-Login.vue

Criação do alert para mensagens de erro.

Criação do alert para mensagens de erro

---

src/views/Mylev-EditSubject.vue

Criação da pagina de editar matéria

Criação da pagina de editar matéria

---

src/App.vue
src/router/index.js
src/views/Mylev-ListSubject.vue

Criação da página para listagem das matérias, criação da rota para a mesma e adicionada margin no container.

Criação da página para listagem das matérias, criação da rota para a mesma

---

src/App.vue
src/components/views/subject/Mylev-TableSubjectCard.vue
src/views/Mylev-ListSubject.vue

Criação do card com a tabela para a listagem das matérias.

Criação do card com a tabela para a listagem das matérias

---

src/router/index.js
src/views/Mylev-AddSubContent.vue

Criação da pagina de criar o subconteudo.

Criação da pagina de criar o subconteudo.

---

src/components/views/subcontent/Mylev-SubContentCard.vue

Criação do card para adicionar o subconteudo.

Criação do card para adicionar o subconteudo.

---

src/components/views/subject/Mylev-SubjectCard.vue
src/components/views/subject/Mylev-TableSubjectCard.vue
src/mixins/loginGoogle.js
src/router/index.js
src/store/modules/Profile/actions.js
src/store/modules/Subject/actions.js
src/store/modules/Subject/getters.js
src/store/modules/Subject/mutationTypes.js
src/store/modules/Subject/mutations.js
src/store/modules/Subject/state.js
src/views/Mylev-EditSubject.vue
src/views/Mylev-Subject.vue

Criação da ação para atualizar uma matéria na página de edição.

Criação da ação para atualizar uma matéria na página de edição

---

src/components/views/subject/Mylev-TableSubjectCard.vue
src/views/Mylev-ListSubject.vue

Criação da ação para deletar uma matéria.

Criação da ação para deletar uma matéria

---

package-lock.json
package.json
src/components/views/subcontent/Mylev-SubContentCard.vue
src/components/views/subject/Mylev-SubjectCard.vue
src/components/views/subject/Mylev-TableSubjectCard.vue
src/configuration/configuration.json
src/store/index.js
src/store/modules/SubContent/actions.js
src/store/modules/SubContent/getters.js
src/store/modules/SubContent/index.js
src/store/modules/SubContent/mutationTypes.js
src/store/modules/SubContent/mutations.js
src/store/modules/SubContent/state.js
src/views/Mylev-AddSubContent.vue

Adicionado parcialmente a requisição para salvar um subconteúdo.

Adicionado parcialmente a requisição para salvar um subconteúdo

---

src/configuration/configuration.json
src/helpers/checkPermission.js
src/helpers/managerCookies.js
src/mixins/loginGoogle.js
src/router/index.js
src/router/subcontent/index.js
src/router/subject/index.js

Organização do arquivo de rotas e realizada a criação da restrição de páginas de acordo com o usuário que está logado(admin, estudante).

Organização do arquivo de rotas e realizada a criação da restrição de páginas

---

src/components/views/login/Mylev-LoginCard.vue
src/router/index.js
src/views/Mylev-ConfirmRegister.vue

Criação da página para confirmar o cadastro do usuário e criada a rota para a página.

Criação da página para confirmar o cadastro do usuário e criada a rota para a página

---

src/components/views/confirmregister/Mylev-ConfirmRegisterCard.vue
src/views/Mylev-ConfirmRegister.vue

Criado o card com o formulário para a confirmação do cadastro.

Criado o card com o formulário para a confirmação do cadastro

---

src/App.vue
src/components/shared/Mylev-NavBar/Mylev-Navbar.vue
src/components/shared/Mylev-NavBar/components/Mylev-AdminOptionsDesktop.vue
src/components/shared/Mylev-NavBar/components/Mylev-AdminOptionsMobile.vue
src/configuration/configuration.json
src/helpers/checkPermission.js
src/main.js
src/router/subcontent/index.js
src/router/subject/index.js

Criação parcial dos menus faltantes e restrição de acesso usando os cookies.

Criação parcial dos menus faltantes e restrição de acesso usando os cookies

---

src/components/shared/Mylev-Dialog.vue
src/components/views/subject/Mylev-TableSubjectCard.vue

Criação do popup de deleção

---

.prettierrc
src/components/views/confirmregister/Mylev-ConfirmRegisterCard.vue
src/components/views/login/Mylev-LoginCard.vue
src/components/views/register/Mylev-RegisterCard.vue
src/components/views/subcontent/Mylev-SubContentCard.vue
src/components/views/subject/Mylev-SubjectCard.vue
src/configuration/configuration.json
src/helpers/emailValidation.js
src/helpers/filesValidation.js
src/helpers/passwordValidation.js
src/mixins/validations/confirmEmailValidation.js
src/mixins/validations/registerValidation.js
src/mixins/validations/subContentValidation.js
src/mixins/validations/subjectValidation.js

Adicionada validações nos formulários.

Adicionada validações nos formulários

---

src/components/views/register/Mylev-RegisterCard.vue
src/configuration/configuration.json
src/helpers/nicknameValidation.js
src/mixins/validations/registerValidation.js

Criado os métodos necessários para a validação do nickname em tempo real.

Criado os métodos necessários para a validação do nickname em tempo real

---

src/components/shared/Mylev-NavBar/components/Mylev-AdminOptionsDesktop.vue
src/components/shared/Mylev-NavBar/components/Mylev-AdminOptionsMobile.vue
src/components/views/subcontent/Mylev-SubContentCard.vue
src/components/views/subject/Mylev-SubjectCard.vue
src/components/views/subject/Mylev-TableSubjectCard.vue
src/store/modules/SubContent/actions.js
src/store/modules/Subject/actions.js
src/views/subcontent/Mylev-AddSubContent.vue
src/views/subcontent/Mylev-ListSubContent.vue
src/views/subcontent/Mylev-SubContent.vue
src/views/subject/Mylev-EditSubject.vue
src/views/subject/Mylev-ListSubject.vue
src/views/subject/Mylev-Subject.vue

Renomeado o nome e conteúdo dos arquivos para ficarem mais concisos.
Renomeada a escrita matéria para disciplina.
Renomeada a escrita subconteúdo para matéria.

Renomeado o nome e conteúdo dos arquivos para ficarem mais concisos

---

src/components/shared/Mylev-Favoritos.vue
src/configuration/configuration.json
src/store/modules/Profile/Bookmark/actions.js
src/store/modules/Profile/Bookmark/getters.js
src/store/modules/Profile/Bookmark/index.js
src/store/modules/Profile/Bookmark/mutationTypes.js
src/store/modules/Profile/Bookmark/mutations.js
src/store/modules/Profile/Bookmark/state.js

Criação do componente de favoritos

Criação do componente de favoritos

---

.prettierrc
src/components/shared/Mylev-Bookmark-Button.vue
src/components/views/profile/Mylev-Bookmarks.vue
src/store/modules/Profile/modules/bookmark/actions.js
src/views/Mylev-Profile.vue
src/views/subcontent/Mylev-SubContent.vue

Criação do botão de favoritos e adicionado os métodos necessários para o mesmo.
Botão ao lado do título de cada matéria.

Criação do botão de favoritos e adicionado os métodos necessários para o mesmo

---

src/components/views/profile/Mylev-Bookmarks.vue
src/components/views/profile/Mylev-Tasks/Mylev-Tasks.vue
src/components/views/profile/Mylev-Tasks/components/Mylev-Tasks-Dialog.vue
src/mixins/dateTime.js
src/mixins/index.js
src/store/modules/Profile/actions.js
src/store/modules/Profile/modules/tasks/actions.js
src/views/Mylev-Profile.vue

Criação do dialogo de tarefas e integração com a API.

Criação do dialogo de tarefas e integração com a API

---

src/components/views/profile/Mylev-Tasks/components/Mylev-Tasks-Dialog.vue
src/mixins/validations/taskValidation.js

Criação da validação dos campos do formulário de tarefa.

Criação da validação dos campos do formulário de tarefa

---

src/App.vue
src/components/shared/Mylev-NavBar/components/Mylev-AdminOptionsDesktop.vue
src/components/shared/Mylev-NavBar/components/Mylev-AdminOptionsMobile.vue
src/components/views/profile/Mylev-Bookmarks.vue
src/components/views/profile/Mylev-Tasks/Mylev-Tasks.vue
src/components/views/subcontent/Mylev-SubContentCard.vue
src/components/views/subcontent/Mylev-TableSubContentCard.vue
src/components/views/subject/Mylev-TableSubjectCard.vue
src/configuration/configuration.json
src/mixins/validations/subContentValidation.js
src/store/modules/SubContent/actions.js
src/store/modules/Subject/actions.js
src/views/subcontent/Mylev-ListSubContent.vue

Criação da página de listagem das máterias(subconteúdo - admin) e funcionalidade de deleção.

Criação da página de listagem das máterias(subconteúdo - admin)

---

src/components/shared/Mylev-ContentName.vue
src/configuration/configuration.json
src/router/subcontent/index.js
src/store/modules/SubContent/actions.js
src/store/modules/SubContent/getters.js
src/store/modules/SubContent/mutationTypes.js
src/store/modules/SubContent/mutations.js
src/store/modules/SubContent/state.js
src/views/Mylev-Home.vue
src/views/subcontent/Mylev-SubContent.vue
src/views/subcontent/Mylev-SubContents.vue

Criação da página de listagem de matérias para o aluno.

Criação da página de listagem de matérias para o aluno

---

src/components/shared/Mylev-ContentName.vue
src/components/shared/Mylev-Footer.vue
src/components/shared/Mylev-NavBar/Mylev-Navbar.vue
src/components/shared/Mylev-Notifications.vue
src/components/views/confirmregister/Mylev-ConfirmRegisterCard.vue
src/components/views/login/Mylev-LoginCard.vue
src/components/views/profile/Mylev-Bookmarks.vue
src/components/views/profile/Mylev-ProfileInfoCard.vue
src/components/views/profile/Mylev-Tasks/Mylev-Tasks.vue
src/components/views/register/Mylev-RegisterCard.vue
src/components/views/subcontent/Mylev-SubContentCard.vue
src/components/views/subcontent/Mylev-TableSubContentCard.vue
src/components/views/subject/Mylev-SubjectCard.vue
src/components/views/subject/Mylev-TableSubjectCard.vue

Adicionada elevação nos cards.

Adicionada elevação nos cards

---

src/components/shared/Mylev-NavBar/Mylev-Navbar.vue

Adicionado ícone nos botões Home do menu.

Adicionado ícone nos botões Home do menu

---

src/App.vue
src/components/shared/Mylev-Alert.vue
src/components/views/profile/Mylev-Bookmarks.vue
src/components/views/profile/Mylev-Tasks/Mylev-Tasks.vue
src/components/views/subcontent/Mylev-SubContentCard.vue
src/components/views/subcontent/Mylev-TableSubContentCard.vue
src/components/views/subject/Mylev-SubjectCard.vue
src/components/views/subject/Mylev-TableSubjectCard.vue
src/mixins/css.js
src/mixins/index.js
src/store/actions.js
src/store/getters.js
src/store/mutationTypes.js
src/store/mutations.js
src/store/state.js
src/views/Mylev-Home.vue
src/views/subcontent/Mylev-SubContent.vue
src/views/subcontent/Mylev-SubContents.vue
src/views/subject/Mylev-EditSubject.vue
src/views/subject/Mylev-ListSubject.vue

Inicio da atualização no componente Mylev-Alert e adicionado o mesmo em algumas páginas.

Inicio da atualização no componente Mylev-Alert e adicionado o mesmo em algumas páginas

---

src/components/views/login/Mylev-LoginCard.vue
src/mixins/loginGoogle.js
src/store/modules/Profile/actions.js
src/views/Mylev-Profile.vue

Resolvido alguns bugs na parte de cadastro e de login.

Resolvido alguns bugs na parte de cadastro e de login

---

src/components/views/profile/Mylev-Bookmarks.vue
src/components/views/profile/Mylev-Tasks/Mylev-Tasks.vue
src/components/views/subcontent/Mylev-SubContentCard.vue
src/components/views/subcontent/Mylev-TableSubContentCard.vue
src/components/views/subject/Mylev-SubjectCard.vue
src/components/views/subject/Mylev-TableSubjectCard.vue
src/views/Mylev-Home.vue
src/views/subcontent/Mylev-ListSubContent.vue
src/views/subcontent/Mylev-SubContents.vue
src/views/subject/Mylev-EditSubject.vue
src/views/subject/Mylev-ListSubject.vue

Adicionado o componente de erro em algumas páginas.

Adicionado o componente de erro em algumas páginas

---

src/components/shared/Mylev-NavBar/Mylev-Navbar.vue
src/components/views/profile/Mylev-ProfileInfoCard.vue
src/components/views/register/Mylev-RegisterCard.vue
src/main.js
src/mixins/loginGoogle.js
src/mixins/validations/registerValidation.js
src/store/actions.js
src/store/getters.js
src/store/modules/Profile/actions.js
src/store/mutationTypes.js
src/store/mutations.js
src/store/state.js

Inicio da implementação da funcionalidade de alterar as informações de perfil.

Inicio da implementação da funcionalidade de alterar as informações de perfil

---

src/views/Mylev-EditSubContent.vue

Criação do card de ediçaõ de subconteudo

Criação do card de ediçaõ de subconteudo
